language: objective-c
osx_image: xcode11.1
before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods --pre --no-document --quiet
script:
  - set -o pipefail && xcodebuild test -workspace Example/EARestrictedScrollView-Example.xcworkspace -scheme Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.1' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
before_deploy:
  - carthage build --no-skip-current
  - carthage archive EARestrictedScrollView
deploy:
  provider: releases
  api_key:
    secure: OJq+c3JV3OtZNGU1BTNULfyWg2aQASMxSaxnjPAanOpOIsDTZLkn4/m/Ty2L2n0C4OamGxyeM7TS50u+ewTQHZAp36n5QjrP4Tyjc/bn3IgfJQJ1X20t4KNjWDSvfwvPYxD9IKFPn/CbQ+kKO6PEI/ogH4/Rx/8XGiuivPsuEU0=
  file: EARestrictedScrollView.framework.zip
  skip_cleanup: true
  on:
    repo: ealeksandrov/EARestrictedScrollView
    tags: true
