language: objective-c
osx_image: xcode7.1
before_install:
  - export LANG=en_US.UTF-8
  - gem i cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/EARestrictedScrollView.xcworkspace -scheme EARestrictedScrollView-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.1' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
